version: '3.4'

services:
  tagtourposts.database:
    image: postgres:latest
    container_name: tagtourposts.database
    environment:
      - POSTGRES_DB=tagtour
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/tagtourposts-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  tagtourposts.api:
    image: ${DOCKER_REGISTRY-}tagtourpostsapi
    container_name: tagtourposts.api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - tagtourposts.database
    ports:
      - "5000:5000"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=ushkandn@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    ports:
      - "5050:80"
